apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.env }}-{{ .Values.appName }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "RCA Platform project – {{ .Values.env }}"
  sourceRepos:
    - "https://github.com/{{ .Values.org }}/{{ .Values.repo }}"
  destinations:
    - namespace: "{{ .Values.env }}-{{ .Values.appName }}"
      server: "{{ .Values.server }}"
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: ""
      kind: Service
    - group: networking.k8s.io
      kind: Ingress
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: spv.no
      kind: AzureKeyVaultSecret
    - group: policy
      kind: PodDisruptionBudget
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: ""
      kind: ServiceAccount
