apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.env }}-{{ .Values.appName }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "RCA Platform project – {{ .Values.env }}"
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
