{{- range .Values.envs }}
{{- $env := . }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $env }}-{{ $.Values.appName }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "RCA Platform project — {{ $env }}"
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
{{- end }}
