# Generated by scripts/apply-config.sh from config.yaml.
# env, server, IngressFrontendHost, IngressBackendHost are set at deploy time via --set flags.
appName: "${APP_NAME}"
org: "${GITHUB_ORG}"
repo: "${GITHUB_REPO}"
env: ""
server: ""
IngressFrontendHost: ""
IngressBackendHost: ""
