{{- if and .Values.keyvault .Values.keyvault.name }}
{{- if .Values.secrets }}
{{- range $i, $s := .Values.secrets }}
{{- if $i }}
---
{{- end }}
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: {{ include "backend.fullname" $ }}-{{ $s | replace "_" "-" | lower }}
  labels:
    {{- include "backend.labels" $ | nindent 4 }}
spec:
  vault:
    name: {{ $.Values.keyvault.name }}
  object:
    name: {{ $s | replace "_" "-" }}
    type: secret
  output:
    secret:
      name: {{ include "backend.fullname" $ }}-{{ $s | replace "_" "-" | lower }}
      dataKey: {{ $s }}
{{- end }}
{{- end }}
{{- end }}
