{{- if .Values.networkPolicy.enabled }}
{{- if and (eq (len .Values.networkPolicy.ingressNamespaceSelector) 0) (eq (len .Values.networkPolicy.ingressPodSelector) 0) }}
{{ fail "networkPolicy.enabled requires ingressNamespaceSelector or ingressPodSelector to have at least one matchLabel" }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        {{- if gt (len .Values.networkPolicy.ingressNamespaceSelector) 0 }}
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.ingressNamespaceSelector | nindent 12 }}
        {{- end }}
        {{- if gt (len .Values.networkPolicy.ingressPodSelector) 0 }}
        - podSelector:
            {{- toYaml .Values.networkPolicy.ingressPodSelector | nindent 12 }}
        {{- end }}
{{- end }}
