{{- if and .Values.artifactoryToken.enabled .Values.secretStore }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "backend.fullname" . }}-docker
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ include "backend.fullname" . }}-docker
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: {{ .Values.secretStore.remotePrefix }}DOCKER_CONFIG_JSON
{{- end }}
