#!/usr/bin/env bash
# Static assertions on the committed repo structure — no script execution required.
# All checks are grep/file-existence based and run instantly.
set -uo pipefail
TESTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$TESTS_DIR/lib.sh"

D="$REPO_ROOT/deployments"
W="$REPO_ROOT/.github/workflows"

echo "--- Static repo structure checks ---"

# Fix 3: CORS annotation — plural form must not exist anywhere
assert_zero_grep \
  "cors-allow-origins (plural) absent from all files" \
  "cors-allow-origins" \
  "$D"

# Fix 1: project.yaml must not use range loop
assert_zero_grep \
  "project.yaml has no range .Values.envs loop" \
  "range .Values.envs" \
  "$D/appset/templates/project.yaml"

assert_nonzero_grep \
  "project.yaml uses .Values.env (singular)" \
  ".Values.env" \
  "$D/appset/templates/project.yaml"

# Fix 4: workflow tpl files exist, generated yaml files do NOT
for env in dev qa stage prod; do
  assert_file_exists \
    "workflow tpl exists: ci-cd-${env}.yaml.tpl" \
    "$W/ci-cd-${env}.yaml.tpl"

  assert_file_absent \
    "non-tpl workflow absent: ci-cd-${env}.yaml" \
    "$W/ci-cd-${env}.yaml"
done

# Fix 4: workflow tpl files contain all three envsubst identity variables
for env in dev qa stage prod; do
  tpl="$W/ci-cd-${env}.yaml.tpl"
  for var in '${APP_NAME}' '${GITHUB_ORG}' '${GITHUB_REPO}'; do
    assert_nonzero_grep \
      "ci-cd-${env}.yaml.tpl references $var" \
      "$var" \
      "$tpl"
  done
done

# Fix 4: appset values.yaml.tpl exists; static values.yaml does not
assert_file_exists \
  "deployments/appset/values.yaml.tpl exists" \
  "$D/appset/values.yaml.tpl"

assert_file_absent \
  "deployments/appset/values.yaml absent (generated by apply-config.sh)" \
  "$D/appset/values.yaml"

# Fix 5: config.yaml comment is correct
assert_nonzero_grep \
  "config.yaml contains corrected comment" \
  "nothing is read from .env" \
  "$REPO_ROOT/config.yaml"

assert_zero_grep \
  "config.yaml has no misleading .env comment" \
  "should also be set in .env" \
  "$REPO_ROOT/config.yaml"

# Fix 7: .helmignore files exist in both charts
assert_file_exists \
  ".helmignore exists in backend chart" \
  "$D/charts/backend/.helmignore"

assert_file_exists \
  ".helmignore exists in frontend chart" \
  "$D/charts/frontend/.helmignore"

# Backend/frontend appset generators both use revision: HEAD
assert_zero_grep \
  "appset.backend.yaml uses HEAD not hardcoded branch" \
  "revision: main" \
  "$D/appset/templates/appset.backend.yaml"

assert_nonzero_grep \
  "appset.backend.yaml revision is HEAD" \
  "revision: HEAD" \
  "$D/appset/templates/appset.backend.yaml"

# All 12 value tpl files use cors-allow-origin (singular)
for env in dev qa stage prod; do
  for svc in api auth; do
    assert_nonzero_grep \
      "backend ${env}/${svc}: cors-allow-origin (singular)" \
      "cors-allow-origin:" \
      "$D/values/backend/${env}/${svc}/values.yaml.tpl"
  done
  assert_nonzero_grep \
    "frontend ${env}/ui: cors-allow-origin (singular)" \
    "cors-allow-origin:" \
    "$D/values/frontend/${env}/ui/values.yaml.tpl"
done

# Dead-config-key guard: every key in config.yaml must be referenced by at least one .tpl file
echo ""
echo "--- Dead config key guard ---"
while IFS= read -r line; do
  [[ "$line" =~ ^[[:space:]]*# ]] && continue
  [[ -z "${line// }" ]] && continue
  [[ "$line" != *:* ]] && continue
  key=$(echo "$line" | cut -d':' -f1 | sed -E 's/^[[:space:]]+//;s/[[:space:]]+$//')
  [[ -z "$key" ]] && continue
  count=$(grep -r "\${${key}}" \
    "$D" "$REPO_ROOT/.github/workflows" \
    --include="*.tpl" 2>/dev/null | wc -l | tr -d '[:space:]')
  [[ "${count:-0}" -gt 0 ]] \
    && _pass "config key ${key} referenced in at least one .tpl" \
    || _fail "config key ${key} is dead — not referenced by any .tpl" ">=1 match" "0"
done < "$REPO_ROOT/config.yaml"

report
