{{- if and .Values.secrets .Values.secretStore }}
{{- range .Values.secrets }}
{{- $secretName := printf "%s--%s" (include "frontend.fullname" $) (. | replace "_" "-" | lower) }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "frontend.labels" $ | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ $secretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $.Values.secretStore.remotePrefix }}{{ . }}
{{- end }}
{{- end }}
