{{- if and .Values.oauth2Proxy.enabled .Values.secretStore }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "frontend.fullname" . }}-oauth2-proxy
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ include "frontend.fullname" . }}-oauth2-proxy
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: {{ .Values.secretStore.remotePrefix }}OAUTH2_CLIENT_ID
    - secretKey: client-secret
      remoteRef:
        key: {{ .Values.secretStore.remotePrefix }}OAUTH2_CLIENT_SECRET
    - secretKey: cookie-secret
      remoteRef:
        key: {{ .Values.secretStore.remotePrefix }}OAUTH2_COOKIE_SECRET
{{- end }}
