{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  {{- if .Values.route.domain }}
  host: {{ .Values.route.domain }}
  {{- end }}
  path: {{ .Values.route.path | default "/" }}
  port:
    targetPort: {{ if .Values.oauth2Proxy.enabled }}oauth2-proxy{{ else }}http{{ end }}
  tls:
    termination: {{ .Values.route.tls.termination }}
  to:
    kind: Service
    name: {{ include "frontend.fullname" . }}
    weight: 100
  wildcardPolicy: None
{{- end }}
