apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.appName }}-{{ .Values.org }}-{{ .Values.env }}
  namespace: {{ .Values.argocdNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "{{ .Values.appName }} – {{ .Values.env }}"
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
